---
title: "report for erosion"
format: pdf
editor: visual
author: "Yingmai Chen"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(readr)
library(gridExtra)
library(car)
library(grid)
library(stats)
library(ggcorrplot)
```

## read data and normalize the data
```{r}
stan <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}
data1 <- read_csv("erosion.csv")# data include max wave height
names(data1) <- gsub(" ", "_", names(data1))
names(data1) <- gsub("\\(", "", names(data1))
names(data1) <- gsub("\\)", "", names(data1))
names(data1) <- gsub("/", "_per_", names(data1))
names(data1) <- gsub("%", "percent", names(data1))
if ("RR (m/yr)" %in% names(data1)) {
  names(data1)[names(data1) == "RR (m/yr)"] <- "RR_m_per_yr"
}

numeric_columns <- sapply(data1, is.numeric) & !names(data1) %in% c("Bluff", "RR_m_per_yr")
data1[numeric_columns] <- lapply(data1[numeric_columns], stan)
data1$RR_m_per_yr <- stan(data1$RR_m_per_yr)
```
```{r}
data2 <- read_csv("erosionnne15.csv")# data include NNE 15 m/s of max waveheight
names(data2) <- gsub(" ", "_", names(data2))
names(data2) <- gsub("\\(", "", names(data2))
names(data2) <- gsub("\\)", "", names(data2))
names(data2) <- gsub("/", "_per_", names(data2))
names(data2) <- gsub("%", "percent", names(data2))
if ("RR (m/yr)" %in% names(data2)) {
  names(data2)[names(data2) == "RR (m/yr)"] <- "RR_m_per_yr"
}
numeric_columns <- sapply(data2, is.numeric) & !names(data2) %in% c("Bluff", "RR_m_per_yr")
data2[numeric_columns] <- lapply(data2[numeric_columns], stan)
data2$RR_m_per_yr <- stan(data2$RR_m_per_yr)

```

## Scatterplot for each variable and boxplot for categorical variable seaWall
```{r}
ggplot(data1,aes(x=Orientation_deg,y=RR_m_per_yr))+
  geom_point()
```

```{r}
ggplot(data1,aes(x=Max_Wave_Height_m,y=RR_m_per_yr))+
  geom_point()
```
```{r}
ggplot(data1,aes(x=Mud_percent,y=RR_m_per_yr))+
  geom_point()
```
```{r}
ggplot(data1,aes(x=BaseEl_m,y=RR_m_per_yr))+
  geom_point()
```

```{r}
ggplot(data1,aes(x=BluffEl_m,y=RR_m_per_yr))+
  geom_point()
```

```{r}
ggplot(data2,aes(x=Wave_Height_for_NNE_wind_15_m_per_s_m,y=RR_m_per_yr))+
  geom_point()
```

```{r}
data1$Seawall <- factor(data1$Seawall)
model <- lm(`RR_m_per_yr` ~ Seawall, data = data1)
summary(model)

ggplot(data1, aes(x = Seawall, y = `RR_m_per_yr`)) +
  geom_boxplot() +
  stat_summary(fun = mean, geom = "point", shape = 20, size = 3, color = "blue")+
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., 2)), vjust = -1) +
  labs(title = "Effect of Seawall on RR (m/yr)", x = "Seawall", y = "RR (m/yr)")
```



## Correlation Matrix of data1(with max wave height)
```{r}
correlationdata1 <- read_csv("correlationdata1.csv")
correlation_matrix1 <- cor(correlationdata1)
print(correlation_matrix1)
```
```{r}
ggcorrplot(correlation_matrix1)
```

## Correlation Matrix of data2(with max wave height on NNE 15m/s)
```{r}
correlationdata2 <- read_csv("correlationdata2.csv")
correlation_matrix2 <- cor(correlationdata2)
print(correlation_matrix2)
```

```{r}
ggcorrplot(correlation_matrix2)
```


## linear regression for data1(with max wave height)

```{r}
target <- "RR_m_per_yr"
predictors <- setdiff(names(data1), c("Bluff", target))
model_formula <- as.formula(paste(target, "~", paste(predictors, collapse = " + ")))

model1 <- lm(model_formula, data = data1)
print(summary(model1))
predictions <- predict(model1, data1)
mse <- mean((data1[[target]] - predictions)^2)
rsquared <- summary(model1)$r.squared
cat("(MSE):", mse, "\n")
cat("R square:", rsquared, "\n")
```

## linear regression for data2(with max wave heigh on NNE 15m/s)

```{r}
target <- "RR_m_per_yr"
predictors <- setdiff(names(data2), c("Bluff", target))
model_formula <- as.formula(paste(target, "~", paste(predictors, collapse = " + ")))

model2 <- lm(model_formula, data = data2)
print(summary(model2))
predictions <- predict(model2, data2)
mse <- mean((data2[[target]] - predictions)^2)
rsquared <- summary(model2)$r.squared
cat("(MSE):", mse, "\n")
cat("R square:", rsquared, "\n")

```