---
title: "eda for erosion"
author: "Yingmai Chen"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(tidyverse)
```


```{r}
erosion<-read.csv("erosion.csv")
```

### linear regression
```{r}
library(readr)
data <- read_csv("erosion.csv")
names(data) <- gsub(" ", "_", names(data))
names(data) <- gsub("\\(", "", names(data))
names(data) <- gsub("\\)", "", names(data))
names(data) <- gsub("/", "_per_", names(data))
names(data) <- gsub("%", "percent", names(data))
if ("RR (m/yr)" %in% names(data)) {
  names(data)[names(data) == "RR (m/yr)"] <- "RR_m_per_yr"
}
predictors <- setdiff(names(data), c("Bluff", "RR_m_per_yr"))
target <- "RR_m_per_yr"
model_formula <- as.formula(paste(target, "~", paste(predictors, collapse = " + ")))
model <- lm(model_formula, data = data)
summary(model)
predictions <- predict(model, data)
mse <- mean((data[[target]] - predictions)^2)
rsquared <- summary(model)$r.squared
cat("Mean Squared Error (MSE):", mse, "\n")
cat("R-squared:", rsquared, "\n")


```
## check

```{r}
#Check Linearity
plot(data[[target]], predictions, main = "Fitted vs. Actuals",
     xlab = "Actual Values", ylab = "Predicted Values")
abline(0, 1)

#Check Homoscedasticity
plot(model, which = 1)

#Check Normal Distribution of Residuals
qqnorm(model$residuals)
qqline(model$residuals)

```



```{r}
data <- read.csv("erosion.csv")  
model1 <- lm(`RR..m.yr.` ~ `Mud....`, data = data)
summary(model)
ggplot(data, aes(x = `Mud....`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on Mud (%)",
       x = "Mud (%)",
       y = "RR (m/yr)")

```
## check 

```{r}
# Plotting Residuals vs Fitted Values
plot(model1$fitted.values, model1$residuals,
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

# Plotting Normal Q-Q plot for Residuals
qqnorm(model1$residuals)
qqline(model1$residuals, col = "red")

```


```{r}
model2 <- lm(`RR..m.yr.` ~ `Wave.Height.for.NNE.wind.15.m.s..m.`, data = data)
summary(model2)
ggplot(data, aes(x = `Wave.Height.for.NNE.wind.15.m.s..m.`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on Wave Height for NNE wind 15m/s",
       x = "Wave Height for NNE wind 15m/s",
       y = "RR (m/yr)")
```
## check 

```{r}
# Residuals vs Fitted Values Plot
plot(model2$fitted.values, model2$residuals,
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

# Normal Q-Q Plot for Residuals
qqnorm(model2$residuals)
qqline(model2$residuals, col = "red")

```

```{r}
model3 <- lm(`RR..m.yr.` ~ `Max.Wave.Height..m.`, data = data)
summary(model3)
ggplot(data, aes(x = `Max.Wave.Height..m.`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on Max Wave Height(m)",
       x = "Max Wave Height(m)",
       y = "RR (m/yr)")
```
## check
```{r}
# Residuals vs Fitted Values Plot
plot(model3$fitted.values, model3$residuals,
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

# Normal Q-Q Plot for Residuals
qqnorm(model3$residuals)
qqline(model3$residuals, col = "red")

```

```{r}
model <- lm(`RR..m.yr.` ~ `BluffEl..m.`, data = data)
summary(model)
ggplot(data, aes(x = `BluffEl..m.`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on BluffEl(m)",
       x = "BluffEl(m)",
       y = "RR (m/yr)")
```
```{r}
model <- lm(`RR..m.yr.` ~ `Orientation..deg.`, data = data)
summary(model)
ggplot(data, aes(x = `Orientation..deg.`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on Orientation(deg)",
       x = "Orientation(deg)",
       y = "RR (m/yr)")
```
`
```{r}
model <- lm(`RR..m.yr.` ~ `BaseEl..m.`, data = data)
summary(model)
ggplot(data, aes(x = `BaseEl..m.`, y = `RR..m.yr.`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  
  labs(title = "Linear Regression of RR (m/yr) on BaseEl(m)",
       x = "BaseEl(m)",
       y = "RR (m/yr)")
```

### factor analysis
```{r}

data$Seawall <- factor(data$Seawall)
model <- lm(`RR..m.yr.` ~ Seawall, data = data)
summary(model)
ggplot(data, aes(x = Seawall, y = `RR..m.yr.`)) +
  geom_boxplot() +
  labs(title = "Effect of Seawall on RR (m/yr)", x = "Seawall", y = "RR (m/yr)")

```
```{r}
data$ErosionVulnerability <- factor(data$ErosionVulnerability)
model <- lm(`RR..m.yr.` ~ ErosionVulnerability, data = data)
summary(model)
ggplot(data, aes(x = ErosionVulnerability, y = `RR..m.yr.`)) +
  geom_boxplot() +
  labs(title = "Effect of ErosionVulnerability on RR (m/yr)", x = "ErosionVulnerability", y = "RR (m/yr)")
```


