---
title: "**Erosion Susceptibility of Boston Harbor Bluffs**"
author:
  - Teaching Fellow - Minh Thu Bui
  - Supervisor - Professor Masanao Yajima
  - Yingmai Chen, Maysen Pagan, Chang Shi, Yan Wang
output: pdf_document
---
```{r, echo = FALSE}
#libraries
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
library(philentropy)
library(cluster)
library(pheatmap)
library(ggpubr)
```

# Project Background

# Objectives

# Exploratory Data Analysis

## Data Cleaning and Organizing 
```{r, echo = FALSE}
#loading and cleaning data
data <- read.csv("erosion_vulnerability.csv")
colnames(data) <- c("bluff", "orientation", "rr", "vulnerability", "wave.height", "max.wave.height", "mud.comp", "base.el", "bluff.el", "seawall")
#remove rows/bluffs with no erosion rate data
data <- data %>% drop_na()
```

```{r, echo = FALSE}
#remove vulnerability for our analysis
bluffs <- data[,-4]
#scale numeric columns
bluffs[,2:8] <- scale(bluffs[,2:8])
```

## Data Exploration

```{r, echo = FALSE}
data %>% ggplot(aes(orientation, rr, col = as.factor(seawall))) + geom_point(alpha=0.5) +
  labs(x = "Degree Orientation",
       y = "Retreat Rate (m/yr)", 
       title = "Orientation vs. Erosion Rates") +
  #theme_bw() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12), 
        plot.title = element_text(size = 16),
        legend.text = element_text(size = 12)
        ) + 
  scale_color_manual(values = c("#587090", "#ff6380"),
                    name = "Seawall Presence") +
  coord_polar() +
  scale_x_continuous(limits = c(0,360),
                     breaks = seq(0, 360, by = 45),
                     minor_breaks = seq(0, 360, by = 15))
```

# Models and Analysis

```{r, echo = FALSE}
#heatmap
gower_samples <- as.dist(as.matrix(daisy(bluffs[,2:9], metric = "gower")))
gower_features <- as.dist(as.matrix(daisy(t(bluffs[,2:9]), metric = "gower")))

pheatmap(bluffs[,2:9], 
                    display_numbers = TRUE, 
                    clustering_distance_rows=gower_samples,
                    clustering_distance_cols=gower_features,
                    angle_col = 3,
                    fontsize = 6,
                    cellheight = 5.6,
                    cellwidth = 13.5
                    )
```

```{r, echo = FALSE, warning = FALSE}
#multidimensional scaling
mds <- gower_samples %>% 
  cmdscale() %>%
  as_tibble()

mds <- as.data.frame(mds)

colnames(mds) <- c("Dimension 1", "Dimension 2")
ggscatter(mds, x = "Dimension 1", y = "Dimension 2", 
          #label = rownames(mds),
          size = 1,
          repel = TRUE, 
          title = "Multidimensional Scaling Plot") +
  theme_bw() +
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 16))


```

# Conclusion

# Appendix












